### ISSUE TITLE
Modification error after converting

### ISSUE THREAD

**Issue by KaiLiCn** [Biobix/proBAMconvert#8] opened 2017-07-25 09:29 UTC
Hi:

When I parsing proBam files which were converted by proBAMconvert, I found some modification error. It lost the location detail, because all modifications I got were 1st site, such as  _0-UNIMOD:4;0-UNIMOD:35_ . However this issue was only found in mzIdentML converting case. 

The mzIdentML files were download from _pride_ as your suggestion, such as PXD001524 and PXD000764. Meanwhile, the parameters were set up according to your tutorial.

Kai.

**Comment by vladie0** [comment] 2017-08-04 07:49
Dear KaiLiCn, 

I investigate the error, and you are right. 
There was a parsing error in the MzIdentML parsing where the location was wrongly extracted in certain scenarios. 

This has now been fixed (pushed to GitHub), I will create patched executables shortly.

Thank you for bringing this issue to our attention,
vladie0

**Comment by KaiLiCn** [comment] 2017-08-08 03:43
Dear vladie0,

Thanks for your updating, I will try new version!

Best regards!

Kai

**Comment by vladie0** [comment] 2017-08-10 04:25
Apologies for the late reply, 

which operating system do you use ? I want to provide you a prototype version to verify whether the application is working as intended

Kind regards,
Vladie

**Comment by KaiLiCn** [comment] 2017-08-10 08:49
Thank you very much, my OS is _windows 10_.

Best regards!

Kai

**Comment by vladie0** [comment] 2017-08-11 03:58
Dear KaiLiCn,

Can you verify whether the following version of proBAMconvert solves your issues ? 
https://drive.google.com/open?id=0B3z-MmiBk77oZE5pSENFRW9YSjg

Thank you

**Comment by KaiLiCn** [comment] 2017-08-13 10:32
Dear Vladie0,

I tried new version of proBAMconvert, and I have got modifications. But, there is a little bug I think you might need to fix it. 

I guess the modifications are from _mzIdentML_, so I compared them. If there is only one single modification in a peptide, the modification is same in these two files. However, when there are multi ones in a peptide, the modifications may replicate on some sites. There are two examples as follow, I list two peptides about their modification in _proBAM_ and _mzIdentML_ file. 

_proBAM_:
The type is XM and value is 18-UNIMOD:4
The type is XP and value is HQPQEFPTYVEPTNDEICEAFR
_mzIdentML_:
    <Peptide id="peptide_12478_1">
      <PeptideSequence>HQPQEFPTYVEPTNDEICEAFR</PeptideSequence>
      <Modification location="18" residues="C" monoisotopicMassDelta="57.021464">
        <cvParam accession="UNIMOD:4" name="Carbamidomethyl" cvRef="UNIMOD" />
      </Modification>
    </Peptide>

_proBAM_:
The type is XM and value is 4-UNIMOD:4;17-UNIMOD:4;17-UNIMOD:4
The type is XP and value is RMPCAEDYLSVVLNQLCVLHEK
_mzIdentML_:
   <Peptide id="peptide_12465_1">
      <PeptideSequence>RMPCAEDYLSVVLNQLCVLHEK</PeptideSequence>
      <Modification location="4" residues="C" monoisotopicMassDelta="57.021464">
        <cvParam accession="UNIMOD:4" name="Carbamidomethyl" cvRef="UNIMOD" />
      </Modification>
      <Modification location="17" residues="C" monoisotopicMassDelta="57.021464">
        <cvParam accession="UNIMOD:4" name="Carbamidomethyl" cvRef="UNIMOD" />
      </Modification>
    </Peptide>

I tested two files and they have same problem. I wish it may help you to fix it.

Best regards!

Kai

**Comment by KaiLiCn** [comment] 2017-08-13 10:35
Dear Vladie0,

I tried new version of proBAMconvert, and I have got modifications. But, there is a little bug I think you might need to fix it.

I guess the modifications are from mzIdentML, so I compared them. If there is only one single modification in a peptide, the modification is same in these two files. However, when there are multi ones in a peptide, the modifications may replicate on some sites. There are two examples as follow, I list two peptides about their modification in proBAM and mzIdentML file.

proBAM:
The type is XM and value is 18-UNIMOD:4
The type is XP and value is HQPQEFPTYVEPTNDEICEAFR
mzIdentML:
> <Peptide id="peptide_12478_1">
      <PeptideSequence>HQPQEFPTYVEPTNDEICEAFR</PeptideSequence>
      <Modification location="18" residues="C" monoisotopicMassDelta="57.021464">
        <cvParam accession="UNIMOD:4" name="Carbamidomethyl" cvRef="UNIMOD" />
      </Modification>
    </Peptide>

proBAM:
The type is XM and value is 4-UNIMOD:4;17-UNIMOD:4;17-UNIMOD:4
The type is XP and value is RMPCAEDYLSVVLNQLCVLHEK
mzIdentML:
> <Peptide id="peptide_12465_1">
      <PeptideSequence>RMPCAEDYLSVVLNQLCVLHEK</PeptideSequence>
      <Modification location="4" residues="C" monoisotopicMassDelta="57.021464">
        <cvParam accession="UNIMOD:4" name="Carbamidomethyl" cvRef="UNIMOD" />
      </Modification>
      <Modification location="17" residues="C" monoisotopicMassDelta="57.021464">
        <cvParam accession="UNIMOD:4" name="Carbamidomethyl" cvRef="UNIMOD" />
      </Modification>
    </Peptide>

I tested two files and they have same problem. I wish it may help you to fix it.

Best regards!

Kai

**Comment by vladie0** [comment] 2017-08-14 04:17
Dear Kai,

Thank you for bringing this up, I'm implementing a fix now and will send you a new executable to test ASAP.

Best Regards,
Vladie

**Comment by vladie0** [comment] 2017-08-16 04:30
Dear Kai, 

The following link contains a patched Windows executable .
https://drive.google.com/open?id=0B3z-MmiBk77oZE5pSENFRW9YSjg

Please let me know whether this version solves your issues, once verified I'll push to public.
Thank you for your collaboration!
Vladie0

**Comment by KaiLiCn** [comment] 2017-08-16 07:13
Dear Vladie0,

I tested this version and it solved my problem perfectly. 

Thanks for your help!

Best regards!

Kai

**Comment by vladie0** [comment] 2017-08-16 07:23
Dear Kai, 

I'm glad it's fixed now, thank you for helping improve proBAMconvert.
If I you experience any other issues, please let us know. proBAMconvert was only recently publicly released and we're continuously looking to improve our software.

Kind Regards,
Vladie0

**Closed** 2017-08-16 07:23 UTC
Labels: bug
